Data Management (for INF-2700): pager.h File Reference
pager.h File Reference
A pager for accessing file blocks through buffer pages.
#include <stdio.h>
#include <stdlib.h>
#include "pmsg.h"
Macros
#define BLOCK_SIZE 512L
#define NUM_PAGES 10
#define PAGE_HEADER_SIZE 20
#define MAX_OPEN_FILES 10
#define INT_SIZE 4
Typedefs
typedef struct block_struct * block_p
typedef struct page_struct * page_p
Functions
void put_file_info (pmsg_level level, const char *fname)
void put_page_info (pmsg_level level, page_p p)
void put_block_info (pmsg_level level, block_p b)
void put_pager_info (pmsg_level level, const char *msg)
void put_pager_profiler_info (pmsg_level level)
void put_pqueues_info (pmsg_level level)
int set_system_dir (char *dir)
char * system_dir ()
int pager_init (void)
void pager_terminate (void)
void pager_profiler_reset (void)
page_p get_page (const char *fname, int blknr)
page_p get_page_for_append (const char *fname)
page_p get_next_page (page_p p)
void page_set_pos_begin (page_p p)
int file_num_blocks (const char *fname)
int close_file (const char *fname)
page_p pin (block_p b)
void unpin (page_p p)
int read_page (page_p p)
int write_page (page_p p)
int page_block_nr (page_p p)
int page_current_pos (page_p p)
int page_set_current_pos (page_p p, int pos)
int page_valid_pos_for_get (page_p p, int offset)
int page_valid_pos_for_put (page_p p, int offset, int len)
int eop (page_p p)
int peof (page_p p)
int page_get_int (page_p p)
int page_put_int (page_p p, int val)
int page_get_int_at (page_p p, int offset)
int page_put_int_at (page_p p, int offset, int val)
int page_get_str (page_p p, char *str, int len)
int page_put_str (page_p p, char *str, int len)
int page_get_str_at (page_p p, int offset, char *str, int len)
int page_put_str_at (page_p p, int offset, char *str, int len)
Variables
int num_file_handles
page_p pages [NUM_PAGES]
Detailed Description
A pager for accessing file blocks through buffer pages.
Author
Weihai Yu
A pager maintains a number of buffer pages in the main memory.
Start a pager with pager_init() and terminate it with pager_terminate().
To process data stored in a table file, use get_page() to get the page of a given block (if there is no page for the block yet, associate a page with the block), or use get_page_for_append() or get_next_page() to get an appropriate page, and then use read_page() to read the content of a block into the page, or write_page() to write the content of a page into the block.
When a page is pinned to a block, it cannot be replaced by another block unless all pages are pinned. unpin() a page to allow the page to be associated with another block.
A page has a current position that can be obtained with page_current_pos(). To access a data value of type x at the current position, use page_get_x() and page_put_x(). To access a value at a particular position, use page_get_x_at() and page_put_x_at().
put_..._info() are useful for printing out various info during debugging.
Reset the pager profiler with pager_profiler_reset() before profiling the pager.
See source code in schema.c for examples of how to use the pager.
Definition in file pager.h.
Macro Definition Documentation
#define BLOCK_SIZE 512L
block size in number of bytes
Definition at line 49 of file pager.h.
Referenced by add_field(), page_valid_pos_for_put(), read_page(), system_dir(), and write_page().
#define INT_SIZE 4
an integer consists of 4 bytes
Definition at line 61 of file pager.h.
Referenced by new_int_field(), page_get_int(), page_get_int_at(), page_put_int(), page_put_int_at(), system_dir(), test_page_read_with_offset(), and test_page_write_with_offset().
#define MAX_OPEN_FILES 10
max number of open files
Definition at line 58 of file pager.h.
Referenced by pager_init(), pager_terminate(), put_pager_info(), and system_dir().
#define NUM_PAGES 10
buffer size in number of pages
Definition at line 52 of file pager.h.
Referenced by file_num_blocks(), pager_init(), pager_terminate(), put_pager_info(), and system_dir().
#define PAGE_HEADER_SIZE 20
number of bytes as page header
Definition at line 55 of file pager.h.
Referenced by add_field(), eot(), get_page(), page_set_pos_begin(), page_valid_pos_for_get(), page_valid_pos_for_put(), read_page(), system_dir(), test_page_read_with_offset(), and test_page_write_with_offset().
Typedef Documentation
typedef struct block_struct* block_p
Definition at line 63 of file pager.h.
typedef struct page_struct* page_p
Definition at line 64 of file pager.h.
Function Documentation
int close_file (const char * fname)
Close the file
Definition at line 695 of file pager.c.
Referenced by remove_table().
int eop (page_p p)
returns true (non-zero) if current position is at the end-of-page
Definition at line 1102 of file pager.c.
References page_struct::current_pos, and page_struct::free_pos.
Referenced by eot(), peof(), test_page_read(), and test_page_read_with_offset().
int file_num_blocks (const char * fname)
Number of blocks in the file
Definition at line 657 of file pager.c.
References file_handle_struct::blocks_in_mem, ERROR, file_handle_struct::fd, file_handle_struct::fname, file_handle_struct::num_blocks, num_file_handles, NUM_PAGES, and put_msg().
Referenced by put_tbl_info().
page_p get_next_page (page_p p)
Get the next page
Definition at line 936 of file pager.c.
References block_struct::blk_nr, page_struct::block, block_struct::fhandle, file_handle_struct::fname, get_page(), and file_handle_struct::num_blocks.
Referenced by append_record(), and eot().
page_p get_page (const char * fname, int blknr)
Get a page for a file block. A block is identified by the file and the block number blknr (starting at 0. blknr = -1 for the last block at the end of the file). get_page() does the following
open_tbl_file() (and open/create the file on demand);
returns the block if it is already managed in the file handle;
otherwise,
make it managed in the file handle;
pin the block to a buffer page (and read the block into the page).
Returns NULL upon failure of getting the page or pinning (reading) the page.
The current position of the page is set to right after the header
Definition at line 879 of file pager.c.
References block_struct::blk_nr, file_handle_struct::current_block, page_struct::current_pos, ERROR, block_struct::fhandle, file_handle_struct::num_blocks, block_struct::page, PAGE_HEADER_SIZE, pin(), and put_msg().
Referenced by get_next_page(), get_page_for_append(), set_tbl_position(), test_page_read(), test_page_read_with_offset(), test_page_write(), and test_page_write_with_offset().
page_p get_page_for_append (const char * fname)
Get the last block and move the current position to the end
Definition at line 927 of file pager.c.
References page_struct::current_pos, page_struct::free_pos, and get_page().
Referenced by append_record(), and set_tbl_position().
int page_block_nr (page_p p)
Return page's block number.
Definition at line 1036 of file pager.c.
References block_struct::blk_nr, page_struct::block, ERROR, and put_msg().
Referenced by append_record(), and eot().
int page_current_pos (page_p p)
Return page's current position.
Definition at line 1046 of file pager.c.
References page_struct::current_pos, ERROR, and put_msg().
Referenced by eot(), and find_record_int_val().
int page_get_int (page_p p)
Retrieve the int value at the current position.
Definition at line 1107 of file pager.c.
References page_struct::content, page_struct::current_pos, FATAL, INT_SIZE, page_valid_pos_for_get(), and put_msg().
Referenced by eot(), and test_page_read().
int page_get_int_at (page_p p, int offset)
Retrieve the int value at offset. The current position is moved to the next value.
Definition at line 1131 of file pager.c.
References page_struct::content, page_struct::current_pos, FATAL, INT_SIZE, page_valid_pos_for_get(), and put_msg().
Referenced by find_record_int_val(), and test_page_read_with_offset().
int page_get_str (page_p p, char * str, int len)
Retrieve the string value at the current position. The return value -1 indicates a failure. It is the resposibility of the program using the pager to manage the returned string memory (i.e., to free the memory when the string is no longer used).
Definition at line 1156 of file pager.c.
References page_struct::content, page_struct::current_pos, FATAL, page_valid_pos_for_get(), and put_msg().
Referenced by eot(), and test_page_read().
int page_get_str_at (page_p p, int offset, char * str, int len)
Retrieve the string value at offset. The return value -1 indicates a failure. It is the resposibility of the program using the pager to manage the returned string memory. The current position is moved to the next value.
Definition at line 1180 of file pager.c.
References page_struct::content, page_struct::current_pos, FATAL, page_valid_pos_for_get(), and put_msg().
Referenced by test_page_read_with_offset().
int page_put_int (page_p p, int val)
Put the int value val at the current position. Returns -1 if there is not enough space at current position. The current position is moved to the next value.
Definition at line 1119 of file pager.c.
References page_struct::content, page_struct::current_pos, page_struct::dirty, INT_SIZE, and page_valid_pos_for_put().
Referenced by find_record_int_val(), put_record(), and test_page_write().
int page_put_int_at (page_p p, int offset, int val)
Put the int value val at offset. Returns -1 if fails (offset out of range)
Definition at line 1143 of file pager.c.
References page_struct::content, page_struct::dirty, INT_SIZE, and page_valid_pos_for_put().
Referenced by test_page_write_with_offset().
int page_put_str (page_p p, char * str, int len)
Put the string value str of length len at the current position. len includes the ending '\n' of the string. Returns -1 if there is not enough space at current position. The current position is moved to the next value.
Definition at line 1168 of file pager.c.
References page_struct::content, page_struct::current_pos, page_struct::dirty, and page_valid_pos_for_put().
Referenced by find_record_int_val(), put_record(), and test_page_write().
int page_put_str_at (page_p p, int offset, char * str, int len)
Put the string value str of length len at offset. len includes the ending '\n' of the string. Returns -1 if fails (offset out of range).
Definition at line 1192 of file pager.c.
References page_struct::content, page_struct::dirty, and page_valid_pos_for_put().
Referenced by test_page_write_with_offset().
int page_set_current_pos (page_p p, int pos)
Set page's current position.
Definition at line 1056 of file pager.c.
References page_struct::current_pos, ERROR, and put_msg().
Referenced by find_record_int_val().
void page_set_pos_begin (page_p p)
Set current position to the beginning
Definition at line 943 of file pager.c.
References page_struct::current_pos, and PAGE_HEADER_SIZE.
Referenced by eot(), and set_tbl_position().
int page_valid_pos_for_get (page_p p, int offset)
Check if offset is valid for getting a value
Definition at line 1068 of file pager.c.
References page_struct::free_pos, PAGE_HEADER_SIZE, page_struct::page_nr, put_msg(), and WARN.
Referenced by eot(), page_get_int(), page_get_int_at(), page_get_str(), and page_get_str_at().
int page_valid_pos_for_put (page_p p, int offset, int len)
Check if offset is valid for putting a value with lenth len
Definition at line 1078 of file pager.c.
References BLOCK_SIZE, page_struct::current_pos, page_struct::free_pos, and PAGE_HEADER_SIZE.
Referenced by eot(), page_put_int(), page_put_int_at(), page_put_str(), and page_put_str_at().
int pager_init (void)
Initiates a pager. Memory of buffer pages are allocated. Must be called first.
Definition at line 703 of file pager.c.
References block_struct::blk_nr, file_handle_struct::blocks_in_mem, ERROR, block_struct::fhandle, file_handle_struct::fname, MAX_OPEN_FILES, file_handle_struct::num_blocks, num_file_handles, NUM_PAGES, block_struct::page, pager_profiler_reset(), pager_terminate(), pages, and put_msg().
Referenced by open_db(), set_system_dir(), test_page_read(), test_page_read_with_offset(), test_page_write(), and test_page_write_with_offset().
void pager_profiler_reset (void)
Reset th pager profiler
Definition at line 229 of file pager.c.
Referenced by pager_init().
void pager_terminate (void)
Terminates a pager. Memory of buffer pages are released. If there are dirty pages, they are writtern back to the file blocks. All open files are closed. Must be called before the program exits.
Definition at line 804 of file pager.c.
References page_struct::block, pqueue::len, MAX_OPEN_FILES, NUM_PAGES, and pages.
Referenced by close_db(), open_db(), pager_init(), set_system_dir(), test_page_read(), test_page_read_with_offset(), test_page_write(), and test_page_write_with_offset().
int peof (page_p p)
returns true (non-zero) if current position is at the end-of-file
Definition at line 786 of file pager.c.
References page_struct::block, file_handle_struct::current_block, eop(), block_struct::fhandle, block_struct::page, page_struct::pinned, and unpin().
Referenced by eot().
page_p pin (block_p b)
Pin the block to a buffer page and read the block into the page.
Definition at line 949 of file pager.c.
References page_struct::block, ERROR, block_struct::page, page_struct::page_nr, page_struct::pinned, put_msg(), and read_page().
Referenced by get_page().
void put_block_info (pmsg_level level, block_p b)
Definition at line 155 of file pager.c.
References append_msg(), block_struct::blk_nr, block_struct::fhandle, file_handle_struct::fname, block_struct::page, page_struct::page_nr, and put_msg().
Referenced by put_page_info().
void put_file_info (pmsg_level level, const char * fname)
Definition at line 118 of file pager.c.
References put_msg().
Referenced by put_tbl_info().
void put_page_info (pmsg_level level, page_p p)
Definition at line 127 of file pager.c.
References append_msg(), page_struct::block, page_struct::current_pos, page_struct::dirty, page_struct::free_pos, page_struct::pinned, put_block_info(), and put_msg().
Referenced by put_pager_info().
void put_pager_info (pmsg_level level, const char * msg)
Definition at line 165 of file pager.c.
References MAX_OPEN_FILES, NUM_PAGES, pages, put_msg(), and put_page_info().
Referenced by test_page_read(), test_page_read_with_offset(), test_page_write(), and test_page_write_with_offset().
void put_pager_profiler_info (pmsg_level level)
Definition at line 191 of file pager.c.
References append_msg(), pqueue::first, pqueue::last, pqueue::len, pq_elm::next, pq_elm::page, page_struct::page_nr, and put_msg().
Referenced by test_page_read(), test_page_read_with_offset(), test_page_write(), test_page_write_with_offset(), test_tbl_read(), and test_tbl_write().
void put_pqueues_info (pmsg_level level)
Definition at line 222 of file pager.c.
int read_page (page_p p)
Read the content of the page from disk. If the content of the page is already uptodate, return immediately.
Definition at line 975 of file pager.c.
References block_struct::blk_nr, page_struct::block, BLOCK_SIZE, page_struct::content, page_struct::dirty, ERROR, file_handle_struct::fd, block_struct::fhandle, PAGE_HEADER_SIZE, and put_msg().
Referenced by pin().
int set_system_dir (char * dir)
Set the directory of the system
Definition at line 238 of file pager.c.
References DEBUG, ERROR, pager_init(), pager_terminate(), put_msg(), and sys_dir.
Referenced by handle_test_options().
char* system_dir ()
Get the directory of the system
Definition at line 264 of file pager.c.
References page_struct::block, BLOCK_SIZE, file_handle_struct::blocks_in_mem, page_struct::content, file_handle_struct::current_block, page_struct::current_pos, page_struct::dirty, ERROR, FATAL, file_handle_struct::fd, pqueue::first, file_handle_struct::fname, page_struct::free_pos, INT_SIZE, pqueue::last, pqueue::len, MAX_OPEN_FILES, pq_elm::next, file_handle_struct::num_blocks, num_file_handles, NUM_PAGES, pq_elm::page, PAGE_HEADER_SIZE, page_struct::page_nr, page_struct::pinned, pq_elm::prev, put_msg(), page_struct::qelm, sys_dir, unpin(), and WARN.
Referenced by put_db_info().
void unpin (page_p p)
Unpin the page. If the page is dirty, write the content back to disk.
Definition at line 967 of file pager.c.
References page_struct::dirty, page_struct::pinned, and write_page().
Referenced by append_record(), eot(), peof(), system_dir(), test_page_read(), test_page_read_with_offset(), test_page_write(), and test_page_write_with_offset().
int write_page (page_p p)
Write the content of the (dirty) page to disk.
Definition at line 1014 of file pager.c.
References block_struct::blk_nr, page_struct::block, BLOCK_SIZE, page_struct::content, page_struct::dirty, ERROR, file_handle_struct::fd, block_struct::fhandle, and put_msg().
Referenced by test_page_write(), test_page_write_with_offset(), and unpin().
Variable Documentation
int num_file_handles
The number of files that are currently open
Definition at line 67 of file pager.h.
Referenced by file_num_blocks(), pager_init(), and system_dir().
page_p pages[NUM_PAGES]
Database buffer
Definition at line 70 of file pager.h.
Referenced by pager_init(), pager_terminate(), and put_pager_info().