Data Management (for INF-2700): pmsg.h File Reference
pmsg.h File Reference
Print a message to stderr when level is higher than the global msglevel.
Enumerations
enum pmsg_level {
FORCE, FATAL, ERROR, WARN,
INFO, DEBUG
}
Functions
void put_msg (pmsg_level level, char *format,...)
Start a new message line.
void append_msg (pmsg_level level, char *format,...)
Appends additional info to the current message line.
Variables
pmsg_level msglevel
Detailed Description
Print a message to stderr when level is higher than the global msglevel.
Author
Weihai Yu
Definition in file pmsg.h.
Enumeration Type Documentation
enum pmsg_level
Enumerator
FORCE
a forced msg
FATAL
a fatal error
ERROR
a handleable error condition
WARN
a warning
INFO
generic (useful) information about system operation
DEBUG
low-level information for developers
Definition at line 9 of file pmsg.h.
Function Documentation
void append_msg (pmsg_level level, char * format, ...)
Appends additional info to the current message line.
Definition at line 35 of file pmsg.c.
References msglevel.
Referenced by put_block_info(), put_field_info(), put_page_info(), put_pager_profiler_info(), and put_record_info().
void put_msg (pmsg_level level, char * format, ...)
Start a new message line.
Definition at line 13 of file pmsg.c.
References DEBUG, ERROR, FATAL, FORCE, INFO, msglevel, and WARN.
Referenced by add_field(), append_record(), create_test_schema(), eot(), equal_record(), field_desc_next(), file_num_blocks(), fill_record(), get_page(), handle_test_options(), interpret(), new_record(), page_block_nr(), page_current_pos(), page_get_int(), page_get_int_at(), page_get_str(), page_get_str_at(), page_set_current_pos(), page_valid_pos_for_get(), pager_init(), pin(), put_block_info(), put_db_info(), put_field_info(), put_file_info(), put_page_info(), put_pager_info(), put_pager_profiler_info(), put_record_info(), put_schema_info(), put_tbl_info(), read_page(), release_record(), remove_schema(), schema_first_fld_desc(), schema_last_fld_desc(), schema_len(), schema_name(), schema_num_flds(), set_system_dir(), system_dir(), table_display(), table_search(), test_page_read(), test_page_read_with_offset(), test_page_write(), test_page_write_with_offset(), test_tbl_read(), test_tbl_write(), and write_page().
Variable Documentation
pmsg_level msglevel
global msg level
Definition at line 19 of file pmsg.h.
Referenced by append_msg(), handle_test_options(), and put_msg().