Data Management (for INF-2700): schema.c File Reference
schema.c File Reference
#include "schema.h"
#include "pmsg.h"
#include <string.h>
Data Structures
struct field_desc_struct
Field descriptor.
struct schema_struct
Table/record schema.
struct tbl_desc_struct
Table descriptor.
Typedefs
typedef struct field_desc_struct field_desc_struct
Field descriptor.
typedef struct schema_struct schema_struct
Table/record schema.
typedef struct tbl_desc_struct tbl_desc_struct
Table descriptor.
Functions
void put_field_info (pmsg_level level, field_desc_p f)
void put_schema_info (pmsg_level level, schema_p s)
void put_tbl_info (pmsg_level level, tbl_p t)
void put_record_info (pmsg_level level, record r, schema_p s)
void put_db_info (pmsg_level level)
field_desc_p new_int_field (const char *name)
field_desc_p new_str_field (const char *name, int len)
int is_int_field (field_desc_p f)
field_desc_p field_desc_next (field_desc_p f)
char * schema_name (schema_p sch)
field_desc_p schema_first_fld_desc (schema_p sch)
field_desc_p schema_last_fld_desc (schema_p sch)
int schema_num_flds (schema_p sch)
int schema_len (schema_p sch)
int open_db (void)
void close_db (void)
schema_p new_schema (const char *name)
tbl_p get_table (const char *name)
schema_p get_schema (const char *name)
void remove_table (tbl_p t)
void remove_schema (schema_p s)
int add_field (schema_p s, field_desc_p f)
record new_record (schema_p s)
void release_record (record r, schema_p s)
void assign_int_field (void *field_p, int int_val)
void assign_str_field (void *field_p, char *str_val)
int fill_record (record r, schema_p s,...)
int equal_record (record r1, record r2, schema_p s)
void set_tbl_position (tbl_p t, tbl_position pos)
int eot (tbl_p t)
int get_record (record r, schema_p s)
int find_record_int_val (record r, schema_p s, int offset, int(*op)(int, int), int val)
int put_record (record r, schema_p s)
int append_record (record r, schema_p s)
void table_display (tbl_p t)
tbl_p table_search (tbl_p t, char *attr, char *op, int val)
tbl_p table_project (tbl_p t, const char *dest_name, int num_fields, char *fields[])
tbl_p table_natural_join (tbl_p left, tbl_p right)
Variables
const char tables_desc_file [] = "db.db"
Typedef Documentation
typedef struct field_desc_struct field_desc_struct
Field descriptor.
typedef struct schema_struct schema_struct
Table/record schema.
A schema is a linked list of field descriptors. All records of a table are of the same length.
typedef struct tbl_desc_struct tbl_desc_struct
Table descriptor.
A table descriptor allows us to find the schema and run-time infomation about the table.
Function Documentation
int add_field (schema_p s, field_desc_p f)
Add a field to the schema
Definition at line 446 of file schema.c.
References BLOCK_SIZE, ERROR, schema_struct::first, schema_struct::last, field_desc_struct::len, schema_struct::len, field_desc_struct::next, schema_struct::num_fields, field_desc_struct::offset, PAGE_HEADER_SIZE, and put_msg().
Referenced by create_test_schema(), and remove_schema().
int append_record (record r, schema_p s)
Append the record to the table file. The current position moves to the new end of the file. Returns -1 if there is some fatal failure.
Definition at line 722 of file schema.c.
References tbl_desc_struct::current_pg, FATAL, schema_struct::first, FORCE, get_next_page(), get_page_for_append(), INFO, is_int_field(), field_desc_struct::name, schema_struct::name, field_desc_struct::next, tbl_desc_struct::num_records, page_block_nr(), put_msg(), tbl_desc_struct::sch, schema_struct::tbl, and unpin().
Referenced by table_project(), table_search(), and test_tbl_write().
void assign_int_field (void * field_p, int int_val)
Assign an int record field. Note the data type of field_pp
Definition at line 507 of file schema.c.
Referenced by eot(), and fill_record().
void assign_str_field (void * field_p, char * str_val)
Assign a str record field. Note the data type of field_pp
Definition at line 512 of file schema.c.
Referenced by fill_record().
void close_db (void)
Close a database
Definition at line 329 of file schema.c.
References db_tables, and pager_terminate().
Referenced by test_tbl_read(), and test_tbl_write().
int eot (tbl_p t)
Whether the current position is at end of table.
Definition at line 596 of file schema.c.
References assign_int_field(), tbl_desc_struct::current_pg, eop(), FATAL, schema_struct::first, get_next_page(), is_int_field(), field_desc_struct::len, schema_struct::len, field_desc_struct::next, page_block_nr(), page_current_pos(), page_get_int(), page_get_str(), PAGE_HEADER_SIZE, page_set_pos_begin(), page_valid_pos_for_get(), page_valid_pos_for_put(), peof(), put_msg(), schema_struct::tbl, and unpin().
Referenced by test_tbl_read().
int equal_record (record r1, record r2, schema_p s)
Compare if two records have equal field values
Definition at line 556 of file schema.c.
References ERROR, schema_struct::first, is_int_field(), field_desc_struct::next, and put_msg().
Referenced by test_tbl_read().
field_desc_p field_desc_next (field_desc_p f)
Returns the next field_desc
Definition at line 161 of file schema.c.
References ERROR, schema_struct::first, schema_struct::last, schema_struct::len, field_desc_struct::name, schema_struct::name, field_desc_struct::next, schema_struct::num_fields, and put_msg().
int fill_record (record r, schema_p s, ...)
Fill a record with values. Example: fill_record (r, s, 1, "A string", 136)
Definition at line 517 of file schema.c.
References assign_int_field(), assign_str_field(), ERROR, schema_struct::first, is_int_field(), field_desc_struct::name, field_desc_struct::next, and put_msg().
Referenced by fill_gen_record().
int find_record_int_val (record r, schema_p s, int offset, int(*)(int, int) op, int val)
Definition at line 666 of file schema.c.
References schema_struct::first, is_int_field(), field_desc_struct::len, schema_struct::len, field_desc_struct::next, page_current_pos(), page_get_int_at(), page_put_int(), page_put_str(), and page_set_current_pos().
Referenced by table_search().
int get_record (record r, schema_p s)
Retrieve the record value at the current position. The current position moves to the next record. Returns 1 when r is updated, 0 when there is no more record, and -1 when something goes wrong.
Definition at line 654 of file schema.c.
Referenced by table_display(), table_project(), and test_tbl_read().
schema_p get_schema (const char * name)
Return an existing schema, NULL if the named schema does not exist.
Definition at line 357 of file schema.c.
References get_table(), and tbl_desc_struct::sch.
Referenced by create_test_schema(), and test_tbl_read().
tbl_p get_table (const char * name)
Return an existing table desc, NULL if the table does not exist.
Definition at line 348 of file schema.c.
References db_tables, schema_struct::name, tbl_desc_struct::next, and tbl_desc_struct::sch.
Referenced by get_schema(), and test_tbl_read().
int is_int_field (field_desc_p f)
Check if this is an int field. Since there are only int and str fields, "not int" means str.
Definition at line 154 of file schema.c.
References INT_TYPE, and field_desc_struct::type.
Referenced by append_record(), eot(), equal_record(), fill_record(), find_record_int_val(), put_field_info(), put_record(), and put_record_info().
field_desc_p new_int_field (const char * name)
Make an int field with name name.
Definition at line 121 of file schema.c.
References INT_SIZE, INT_TYPE, field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, and field_desc_struct::type.
Referenced by create_test_schema().
record new_record (schema_p s)
Creates a new record of schema s. It is the responsibility of the using program to free the memory of the resulting record using release_record().
Definition at line 473 of file schema.c.
References ERROR, schema_struct::first, field_desc_struct::len, field_desc_struct::next, schema_struct::num_fields, and put_msg().
Referenced by table_display(), table_project(), table_search(), test_data_gen(), and test_tbl_read().
schema_p new_schema (const char * name)
Make a new schema and add it to the current database
Definition at line 336 of file schema.c.
References tbl_desc_struct::current_pg, db_tables, tbl_desc_struct::next, tbl_desc_struct::num_records, tbl_desc_struct::sch, and schema_struct::tbl.
Referenced by create_test_schema(), and remove_schema().
field_desc_p new_str_field (const char * name, int len)
Make an string field with name name and length len.
Definition at line 133 of file schema.c.
References field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, STR_TYPE, and field_desc_struct::type.
Referenced by create_test_schema().
int open_db (void)
Open a database at new_db_dir. If dir is NULL, re-open a prviously openned database. return -1 upon failure.
Definition at line 321 of file schema.c.
References pager_init(), and pager_terminate().
Referenced by test_tbl_read(), and test_tbl_write().
void put_db_info (pmsg_level level)
Definition at line 110 of file schema.c.
References db_tables, tbl_desc_struct::next, put_msg(), put_tbl_info(), and system_dir().
Referenced by test_tbl_write().
void put_field_info (pmsg_level level, field_desc_p f)
Definition at line 44 of file schema.c.
References append_msg(), is_int_field(), field_desc_struct::len, field_desc_struct::name, field_desc_struct::next, field_desc_struct::offset, and put_msg().
Referenced by put_schema_info().
int put_record (record r, schema_p s)
Put the record value at the current position. The current position moves to the next record. Returns -1 if there is not enough space at current position.
Definition at line 704 of file schema.c.
References tbl_desc_struct::current_pg, schema_struct::first, is_int_field(), field_desc_struct::len, field_desc_struct::next, page_put_int(), page_put_str(), and schema_struct::tbl.
void put_record_info (pmsg_level level, record r, schema_p s)
Definition at line 92 of file schema.c.
References append_msg(), schema_struct::first, is_int_field(), field_desc_struct::next, and put_msg().
Referenced by table_project(), table_search(), and test_tbl_read().
void put_schema_info (pmsg_level level, schema_p s)
Definition at line 63 of file schema.c.
References schema_struct::first, schema_struct::len, schema_struct::name, field_desc_struct::next, schema_struct::num_fields, put_field_info(), and put_msg().
Referenced by create_test_schema(), and put_tbl_info().
void put_tbl_info (pmsg_level level, tbl_p t)
Definition at line 78 of file schema.c.
References file_num_blocks(), schema_struct::name, tbl_desc_struct::num_records, put_file_info(), put_msg(), put_schema_info(), and tbl_desc_struct::sch.
Referenced by put_db_info().
void release_record (record r, schema_p s)
Release the memory allocated for the record and its fields.
Definition at line 492 of file schema.c.
References ERROR, schema_struct::num_fields, and put_msg().
Referenced by table_display(), table_project(), table_search(), and test_tbl_read().
void remove_schema (schema_p s)
Remove a schema from the current database
Definition at line 387 of file schema.c.
References add_field(), ERROR, schema_struct::first, field_desc_struct::len, field_desc_struct::name, schema_struct::name, new_schema(), field_desc_struct::next, field_desc_struct::offset, put_msg(), remove_schema(), remove_table(), schema_struct::tbl, and field_desc_struct::type.
Referenced by create_test_schema(), and remove_schema().
void remove_table (tbl_p t)
Remove a table from the current database
Definition at line 366 of file schema.c.
References close_file(), db_tables, schema_struct::name, tbl_desc_struct::next, and tbl_desc_struct::sch.
Referenced by remove_schema().
field_desc_p schema_first_fld_desc (schema_p sch)
Return the first field_desc of schema.
Definition at line 210 of file schema.c.
References ERROR, schema_struct::first, and put_msg().
field_desc_p schema_last_fld_desc (schema_p sch)
Return the last field_desc of schema.
Definition at line 220 of file schema.c.
References ERROR, schema_struct::last, and put_msg().
int schema_len (schema_p sch)
Return length of schema in number of bytes.
Definition at line 240 of file schema.c.
References ERROR, schema_struct::len, and put_msg().
char* schema_name (schema_p sch)
Return name of schema.
Definition at line 200 of file schema.c.
References ERROR, schema_struct::name, and put_msg().
Referenced by fill_gen_record().
int schema_num_flds (schema_p sch)
Return number of fields in schema.
Definition at line 230 of file schema.c.
References ERROR, schema_struct::num_fields, and put_msg().
void set_tbl_position (tbl_p t, tbl_position pos)
Set the current position to the beginning or end of the table.
Definition at line 582 of file schema.c.
References tbl_desc_struct::current_pg, get_page(), get_page_for_append(), schema_struct::name, page_set_pos_begin(), tbl_desc_struct::sch, TBL_BEG, and TBL_END.
Referenced by table_display(), table_project(), table_search(), and test_tbl_read().
void table_display (tbl_p s)
Print all rows of a table.
Definition at line 792 of file schema.c.
References FORCE, get_record(), new_record(), put_msg(), release_record(), tbl_desc_struct::sch, set_tbl_position(), and TBL_BEG.
tbl_p table_natural_join (tbl_p left, tbl_p right)
Join two tables and return the joined table.
Definition at line 868 of file schema.c.
tbl_p table_project (tbl_p t, const char * dest_name, int num_fields, char * fields[])
Make a new table as a result of project.
Definition at line 845 of file schema.c.
References append_record(), DEBUG, get_record(), new_record(), put_record_info(), release_record(), tbl_desc_struct::sch, set_tbl_position(), schema_struct::tbl, and TBL_BEG.
tbl_p table_search (tbl_p t, char * attr, char * op, int val)
Make a new table as the result of a search.
Definition at line 809 of file schema.c.
References append_record(), DEBUG, ERROR, find_record_int_val(), schema_struct::first, INT_TYPE, field_desc_struct::name, schema_struct::name, new_record(), field_desc_struct::next, field_desc_struct::offset, put_msg(), put_record_info(), release_record(), tbl_desc_struct::sch, set_tbl_position(), schema_struct::tbl, TBL_BEG, and field_desc_struct::type.
Variable Documentation
const char tables_desc_file[] = "db.db"
Definition at line 250 of file schema.c.