Data Management (for INF-2700): testpager.c File Reference
testpager.c File Reference
#include "testpager.h"
#include "pmsg.h"
#include <string.h>
Macros
#define NUM_BLOCKS_IN_FILE 20 /* can be greater than NUM_PAGES */
#define NUM_RECORDS_IN_BLOCK 3
Functions
void test_page_write (const char *fname)
void test_page_read (const char *fname)
void test_page_write_with_offset (const char *fname)
void test_page_read_with_offset (const char *fname)
Macro Definition Documentation
#define NUM_BLOCKS_IN_FILE 20 /* can be greater than NUM_PAGES */
Definition at line 5 of file testpager.c.
Referenced by test_page_read(), test_page_read_with_offset(), test_page_write(), and test_page_write_with_offset().
#define NUM_RECORDS_IN_BLOCK 3
Definition at line 6 of file testpager.c.
Referenced by test_page_write(), and test_page_write_with_offset().
Function Documentation
void test_page_read (const char * fname)
Definition at line 56 of file testpager.c.
References eop(), FATAL, get_page(), INFO, NUM_BLOCKS_IN_FILE, page_get_int(), page_get_str(), pager_init(), pager_terminate(), put_msg(), put_pager_info(), put_pager_profiler_info(), and unpin().
void test_page_read_with_offset (const char * fname)
Definition at line 153 of file testpager.c.
References eop(), FATAL, get_page(), INFO, INT_SIZE, NUM_BLOCKS_IN_FILE, page_get_int_at(), page_get_str_at(), PAGE_HEADER_SIZE, pager_init(), pager_terminate(), put_msg(), put_pager_info(), put_pager_profiler_info(), and unpin().
void test_page_write (const char * fname)
Definition at line 12 of file testpager.c.
References FATAL, get_page(), INFO, NUM_BLOCKS_IN_FILE, NUM_RECORDS_IN_BLOCK, page_put_int(), page_put_str(), pager_init(), pager_terminate(), put_msg(), put_pager_info(), put_pager_profiler_info(), unpin(), and write_page().
void test_page_write_with_offset (const char * fname)
Definition at line 111 of file testpager.c.
References FATAL, get_page(), INFO, INT_SIZE, NUM_BLOCKS_IN_FILE, NUM_RECORDS_IN_BLOCK, PAGE_HEADER_SIZE, page_put_int_at(), page_put_str_at(), pager_init(), pager_terminate(), put_msg(), put_pager_info(), put_pager_profiler_info(), unpin(), and write_page().