Data Management (for INF-2700): testmain.c File Reference
testmain.c File Reference
#include "test_data_gen.h"
#include "testschema.h"
#include "pmsg.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
void handle_test_options (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
void handle_test_options (int argc, char * argv[])
Definition at line 10 of file testmain.c.
References DEBUG, ERROR, FATAL, INFO, msglevel, put_msg(), set_system_dir(), and WARN.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 62 of file testmain.c.
References handle_test_options(), prepare_test_data_gen(), test_tbl_read(), and test_tbl_write().