Data Management (for INF-2700): testschema.h File Reference
testschema.h File Reference
#include "schema.h"
Functions
void test_tbl_write (const char *tbl_name)
void test_tbl_read (const char *tbl_name)
void test_tbl_natural_join (const char *my_tbl, const char *yr_tbl)
Function Documentation
void test_tbl_natural_join (const char * my_tbl, const char * yr_tbl)
void test_tbl_read (const char * tbl_name)
Definition at line 46 of file testschema.c.
References close_db(), eot(), equal_record(), ERROR, FATAL, get_record(), get_schema(), get_table(), in_recs, INFO, new_record(), NUM_RECORDS, open_db(), put_msg(), put_pager_profiler_info(), put_record_info(), release_record(), tbl_desc_struct::sch, set_tbl_position(), and TBL_BEG.
Referenced by main().
void test_tbl_write (const char * tbl_name)
Definition at line 13 of file testschema.c.
References append_record(), close_db(), create_test_schema(), DEBUG, in_recs, INFO, INT_TYPE, NUM_RECORDS, open_db(), put_db_info(), put_msg(), put_pager_profiler_info(), tbl_desc_struct::sch, STR_TYPE, and test_data_gen().
Referenced by main().