Data Management (for INF-2700): testschema.c File Reference
testschema.c File Reference
#include <string.h>
#include "testschema.h"
#include "test_data_gen.h"
#include "pmsg.h"
Macros
#define NUM_RECORDS 1000
Functions
void test_tbl_write (const char *tbl_name)
void test_tbl_read (const char *tbl_name)
Variables
record in_recs [NUM_RECORDS]
Macro Definition Documentation
#define NUM_RECORDS 1000
Definition at line 6 of file testschema.c.
Referenced by test_tbl_read(), and test_tbl_write().
Function Documentation
void test_tbl_read (const char * tbl_name)
Definition at line 46 of file testschema.c.
References close_db(), eot(), equal_record(), ERROR, FATAL, get_record(), get_schema(), get_table(), in_recs, INFO, new_record(), NUM_RECORDS, open_db(), put_msg(), put_pager_profiler_info(), put_record_info(), release_record(), tbl_desc_struct::sch, set_tbl_position(), and TBL_BEG.
Referenced by main().
void test_tbl_write (const char * tbl_name)
Definition at line 13 of file testschema.c.
References append_record(), close_db(), create_test_schema(), DEBUG, in_recs, INFO, INT_TYPE, NUM_RECORDS, open_db(), put_db_info(), put_msg(), put_pager_profiler_info(), tbl_desc_struct::sch, STR_TYPE, and test_data_gen().
Referenced by main().
Variable Documentation
record in_recs[NUM_RECORDS]
Definition at line 10 of file testschema.c.
Referenced by test_tbl_read(), and test_tbl_write().